ROLE_PERMISSIONS = {
    "super_admin": {
        "platform.manage",
        "company.create",
        "company.update",
        "company.members.manage",
        "project.create",
        "project.update",
        "project.assignments.manage",
        "job.post",
        "job.apply",
        "crm.clients.manage",
        "crm.leads.manage",
        "invoices.create",
        "invoices.update",
        "invoices.payments.record",
        "reports.view",
        "worker.profile.manage",
        "client.portal.view",
    },
    "company_owner": {
        "company.create",
        "company.update",
        "company.members.manage",
        "project.create",
        "project.update",
        "project.assignments.manage",
        "job.post",
        "job.apply",
        "crm.clients.manage",
        "crm.leads.manage",
        "invoices.create",
        "invoices.update",
        "invoices.payments.record",
        "reports.view",
        "worker.profile.manage",
        "client.portal.view",
    },
    "company_admin": {
        "company.update",
        "company.members.manage",
        "project.create",
        "project.update",
        "project.assignments.manage",
        "job.post",
        "job.apply",
        "crm.clients.manage",
        "crm.leads.manage",
        "invoices.create",
        "invoices.update",
        "invoices.payments.record",
        "reports.view",
        "worker.profile.manage",
        "client.portal.view",
    },
    "manager": {
        "project.create",
        "project.update",
        "project.assignments.manage",
        "job.post",
        "job.apply",
        "crm.clients.manage",
        "crm.leads.manage",
        "invoices.create",
        "invoices.update",
        "invoices.payments.record",
        "reports.view",
        "worker.profile.manage",
        "client.portal.view",
    },
    "worker": {"job.apply", "worker.profile.manage"},
    "client": {"client.portal.view"},
}


def has_permission(role: str, permission: str) -> bool:
    if role == "super_admin":
        return True
    return permission in ROLE_PERMISSIONS.get(role, set())
